### ISSUE TITLE
Does this plugin implement quick fix?

### ISSUE THREAD

**Issue by honzik20** [errata-ai/LSP-vale-ls#3]
I've got this installed and it lints perfectly but I don't get a quick fix action.

**Comment by jdkato** [comment]
Yes, so long as the rules you're using define an action.

**Comment by honzik20** [comment]
I'm afraid it doesn't work for me. (Sublime Text Build 4143)

I've got this style:

```
extends: existence
message: "Don't use end punctuation in headings."
link: https://docs.microsoft.com/en-us/style-guide/punctuation/periods
nonword: true
level: warning
scope: heading
action:
  name: edit
  params:
    - remove
    - '.?!'
tokens:
  - '[a-z][.?!](?:\s|$)'
```

But I only get a copy button:

![image](https://github.com/errata-ai/LSP-vale-ls/assets/16607402/128d1d02-178f-490b-b69e-453b6e7bacb1)

Thanks for this amazing tool, by the way. Rolling out in a team of eight writers and they're lapping it up.
